name: hildr check

on:
  pull_request_target:
    branches: [ main ]

jobs:
  approve:
    runs-on: ubuntu-latest

    steps:
      - name: Approve
        run: echo "build need secrets environment variable, needs approve"

  build:
    runs-on: ubuntu-latest
    needs: [approve]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: 20
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        env:
          ETH_API_KEY: ${{ secrets.ETH_API_KEY }}
          OPT_API_KEY: ${{ secrets.OPT_API_KEY }}
        run: ./gradlew build

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: hildr-node/build/reports/jacoco/test/jacocoTestReport.csv

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: hildr-node/build/reports/jacoco/
